accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from accounts.views import send_login_email, login

urlpatterns = [
    url(r'send_login_email$', send_login_email, name='send-login-email'),
    url(r'login$', login, name='login'),
    url(r'logout$', logout, {'next_page': '/'}, name='logout')
]

lists/urls.py
from django.conf.urls import url

from lists.views import view_list, new_list, my_lists

urlpatterns = [
    url(r'^new$', new_list, name='new-list'),
    url(r'^(\d+)$', view_list, name='view-list'),
    url(r'^users/(.+)$', my_lists, name='my-lists'),
]

tdd_chimera/urls.py
from django.conf.urls import url, include

from lists.views import home_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^lists/', include('lists.urls', namespace='lists')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
import uuid

from django.contrib import auth
from django.db.models import Model, EmailField, CharField

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class Token(Model):
    email = EmailField()
    uid = CharField(default=uuid.uuid4, max_length=40)


class User(Model):
    email = EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'

    is_anonymous = False
    is_authenticated = True

lists/models.py
from django.conf import settings
from django.db.models import ForeignKey
from django.db.models import Model, TextField
from django.urls import reverse


class List(Model):
    owner = ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    @property
    def name(self):
        return self.item_set.first().text

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

    def get_absolute_url(self):
        return reverse('lists:view-list', args=[self.id])


class Item(Model):
    text = TextField(default='')
    list = ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm, Form
from django.forms.fields import TextInput

from lists.models import Item, List

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(ModelForm):
    use_required_attribute = False

    class Meta:
        model = Item
        fields = ['text', ]
        widgets = {
            'text': TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg'
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return ModelForm.save(self)


class NewListForm(Form):
    text = forms.CharField()

    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])

accounts/views.py
from django.contrib import messages, auth
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse

from accounts.models import Token


def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('accounts:login') + '?token=' + str(token.uid)
    )
    message_body = 'Use this link to log in:\n\n{url}'.format(url=url)
    send_mail(
        'Your login link for Superlists',
        message_body,
        'noreply@superlists',
        [email]
    )
    messages.success(
        request,
        "Check your email, we've sent you a link you can use to log in."
    )
    return redirect('/')


def login(request):
    user = auth.authenticate(uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect

from lists.forms import ItemForm, ExistingListItemForm, NewListForm
from lists.models import List

User = get_user_model()


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)

    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, 'form': form})


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, "my_lists.html", {'owner': owner})

lists/templates/base.html
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>To-Do lists</title>
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/css/base.css">
</head>

<body>
<div class="container">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Superlists</a>
      {% if user.email %}
        <ul class="nav navbar-nav navbar-left">
          <li><a href="{% url 'lists:my-lists' user.email %}">My lists</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="navbar-text">Logged in as {{ user.email }}</li>
          <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
        </ul>
      {% else %}
        <form class="navbar-form navbar-right" method="post" action="{% url 'accounts:send-login-email' %}">
          <span>Enter email to log in:</span>
          <input class="form-control" name="email" type="text">
          {% csrf_token %}
        </form>
      {% endif %}
    </div>
  </nav>

  {% if messages %}
    <div class="row">
      <div class="col-md-8">
        {% for message in messages %}
          {% if message.level_tag == 'success' %}
            <div class="alert alert-success">{{ message }}</div>
          {% else %}
            <div class="alert alert-warning">{{ message }}</div>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  {% endif %}
  <div class="row">
    <div class="col-md-6 offset-md-3 jumbotron">
      <div class="text-center">
        <h1>{% block header_text %}{% endblock %}</h1>
        {% block list_form %}
          <form method="POST" action="{% block form_action %}{% endblock %}">
            {% csrf_token %}
            {{ form.text }}
            {% if form.errors %}
              <div class="form-group has-error">
                <span class="help-block">{{ form.text.errors }}</span>
              </div>
            {% endif %}
          </form>
        {% endblock %}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      {% block table %}{% endblock %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      {% block extra_content %}
      {% endblock %}
    </div>
  </div>
</div>
<script src="http://code.jquery.com/jquery.min.js"></script>
<script src="/static/js/list.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        window.Superlists.initialize();
    })
</script>
</body>

</html>

lists/templates/home.html
{% extends "base.html" %}
{% block headr_text %}Start a new To-Do list{% endblock %}
{% block form_action %}{% url 'lists:new-list' %}{% endblock %}

lists/templates/list.html
{% extends "base.html" %}
{% block headr_text %}Your To-Do list{% endblock %}
{% block form_action %}{% url 'lists:view-list' list.id %}{% endblock %}
{% block table %}
    <table class="table" id="id_list_table">
        {% for item in list.item_set.all %}
            <tr>
                <td>{{ forloop.counter }}: {{ item.text }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}
{% block header_text %}My lists{% endblock %}
{% block list_form %}{% endblock %}
{% block extra_content %}
  <h2>{{ owner.email }}'s lists</h2>
  <ul>
    {% for list in owner.list_set.all %}
      <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}